### ISSUE TITLE
Add zip extractor

### ISSUE THREAD

**Issue by oneturkmen** [oneturkmen/automated-grading#3]
Currently, `extract_tars.py` file contains the code that extracts only tar files. Maybe we could also extract zip files? You could create either another script (e.g. `extract_zips.py`), or add functionality into the same file.

Related: https://stackoverflow.com/questions/3451111/unzipping-files-in-python

**Comment by luchiago** [comment]
Hi, I would like to work on this.

**Comment by oneturkmen** [comment]
Go ahead! :)

**Comment by luchiago** [comment]
I was wondering if we should not stop the script if it has more than one .zip. What do you think about?

**Comment by oneturkmen** [comment]
When students submit files, they usually submit a single `tar` or `zip` file. If there's more than 1 inside some directory, then we should throw an error and stop the script (pretty much what it is doing now).

**Comment by luchiago** [comment]
Ok, I understand now.
