### ISSUE TITLE
Integrate folder rename command

### ISSUE THREAD

**Issue by oneturkmen** [oneturkmen/automated-grading#4]
We should integrate the call to Unix-based `rename` command so that it changes spaces to underscores. For example, folder "John Doe 123" will become "John_Doe_123". This command should be run before any compilation is done; so it could be used inside `compile_files.py`, or as a separate script (could be placed inside `/util` folder).

**Comment by SaxenaKartik** [comment]
I would like to work on this

**Comment by oneturkmen** [comment]
Go ahead! :)
